#freemarker
spring:
  freemarker:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  application:
    name: x-space
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
server:
  port: 8888
  context-path: /
#  session:
logging:
  level:
    me:
      leiho:
        blog:
          mapper: debug
  file: log/x-space/debug.log
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: me.leiho.blog