#THYMELEAF
spring:
  thymeleaf:
    cache: false #开发时需要关闭
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: utf-8
#    excluded-view-names:
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
#    template-resolver-order:
#    view-names:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
server:
  port: 8888
  context-path: /
  session:
    timeout: 60
logging:
  level:
    me:
      leiho:
        blog:
          mapper: debug
  file: log/x-space/debug.log