#freemarker
spring:
  freemarker:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://106.15.93.130:3306/www_xaoei_top?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: www_xaoei_top
    password: AwAfeaZDCyZrNer8
  application:
    name: xaoei
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
server:
  port: 12321
  context-path: /
#  session:
logging:
  level:
    me:
      leiho:
        blog:
          mapper: info
  file: logs/info.log
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: me.leiho.blog
sync:
  accesskey: AKIDRqHcpy56whXEoHmXVKya5KQp5B5iuZWQ
  secretkey: ensvBcu1ynvwmZk8naFj8dwyso7FDB0m
  region_name: ap-shanghai
  bucketName: blog-1252251484
