#freemarker
spring:
  freemarker:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://47.100.164.32:3306/blog?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: blog
    password: dabfe4bb67715139ac127146c76e35c3
  application:
    name: x-space
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
server:
  port: 12321
  context-path: /
#  session:
logging:
  level:
    me:
      leiho:
        blog:
          mapper: info
  file: logs/info.log
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: me.leiho.blog